# Filterbank config
filterbank:
  name: 'stft'
  n_filters: 512
  kernel_size: 128
  stride: 32
# Network config
masknet:
  in_chan: 512
  n_src: 2
  out_chan: 512
  bn_chan: 256
  hid_size: 256
  chunk_size: 250
  hop_size: 125
  n_repeats: 6
  mask_act: 'sigmoid'
  bidirectional: true
  dropout: 0.1
# Training config
training:
  epochs: 200
  batch_size: 4
  num_workers: 4
  half_lr: yes
  early_stop: yes
  gradient_clipping: 5
  mixture_consistency: false
# Optim config
optim:
  optimizer: adam
  lr: 0.001
  weight_decay: 1.0e-05
# Data config
data:
  train_dir: data/wav8k/min/tr/
  valid_dir: data/wav8k/min/cv/
  task: sep_reverb_noisy
  nondefault_nsrc:
  noise_src: false
  sample_rate: 8000
  mode: min
